/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_def = 1,
  sym_positive_int = 2,
  sym_negative_int = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  sym_dup = 6,
  sym_swap = 7,
  sym_add = 8,
  sym_sub = 9,
  sym_mul = 10,
  sym_div = 11,
  sym_eq = 12,
  sym_ne = 13,
  sym_gt = 14,
  sym_lt = 15,
  sym_gte = 16,
  sym_lte = 17,
  sym_and = 18,
  sym_or = 19,
  sym_not = 20,
  sym_print = 21,
  anon_sym_GT_DOLLAR = 22,
  anon_sym_DOLLAR = 23,
  anon_sym_if = 24,
  anon_sym_else = 25,
  sym_identifier = 26,
  anon_sym_COLON = 27,
  anon_sym_QMARK = 28,
  anon_sym_LPAREN = 29,
  anon_sym_DASH_GT = 30,
  anon_sym_RPAREN = 31,
  anon_sym_Int = 32,
  anon_sym_Char = 33,
  sym_source_file = 34,
  sym_def = 35,
  sym_int = 36,
  sym_grouping = 37,
  sym_builtin = 38,
  sym_local_bind = 39,
  sym_local_var = 40,
  sym_if = 41,
  sym_expression = 42,
  sym_manual_signature = 43,
  sym_doc_signature = 44,
  sym_signature = 45,
  sym_type = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_grouping_repeat1 = 48,
  aux_sym_signature_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_def] = "def",
  [sym_positive_int] = "positive_int",
  [sym_negative_int] = "negative_int",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_dup] = "dup",
  [sym_swap] = "swap",
  [sym_add] = "add",
  [sym_sub] = "sub",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_gt] = "gt",
  [sym_lt] = "lt",
  [sym_gte] = "gte",
  [sym_lte] = "lte",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_not] = "not",
  [sym_print] = "print",
  [anon_sym_GT_DOLLAR] = ">$",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_RPAREN] = ")",
  [anon_sym_Int] = "Int",
  [anon_sym_Char] = "Char",
  [sym_source_file] = "source_file",
  [sym_def] = "def",
  [sym_int] = "int",
  [sym_grouping] = "grouping",
  [sym_builtin] = "builtin",
  [sym_local_bind] = "local_bind",
  [sym_local_var] = "local_var",
  [sym_if] = "if",
  [sym_expression] = "expression",
  [sym_manual_signature] = "manual_signature",
  [sym_doc_signature] = "doc_signature",
  [sym_signature] = "signature",
  [sym_type] = "type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_grouping_repeat1] = "grouping_repeat1",
  [aux_sym_signature_repeat1] = "signature_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_def] = anon_sym_def,
  [sym_positive_int] = sym_positive_int,
  [sym_negative_int] = sym_negative_int,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_dup] = sym_dup,
  [sym_swap] = sym_swap,
  [sym_add] = sym_add,
  [sym_sub] = sym_sub,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_gt] = sym_gt,
  [sym_lt] = sym_lt,
  [sym_gte] = sym_gte,
  [sym_lte] = sym_lte,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_not] = sym_not,
  [sym_print] = sym_print,
  [anon_sym_GT_DOLLAR] = anon_sym_GT_DOLLAR,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Char] = anon_sym_Char,
  [sym_source_file] = sym_source_file,
  [sym_def] = sym_def,
  [sym_int] = sym_int,
  [sym_grouping] = sym_grouping,
  [sym_builtin] = sym_builtin,
  [sym_local_bind] = sym_local_bind,
  [sym_local_var] = sym_local_var,
  [sym_if] = sym_if,
  [sym_expression] = sym_expression,
  [sym_manual_signature] = sym_manual_signature,
  [sym_doc_signature] = sym_doc_signature,
  [sym_signature] = sym_signature,
  [sym_type] = sym_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_grouping_repeat1] = aux_sym_grouping_repeat1,
  [aux_sym_signature_repeat1] = aux_sym_signature_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [sym_positive_int] = {
    .visible = true,
    .named = true,
  },
  [sym_negative_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_dup] = {
    .visible = true,
    .named = true,
  },
  [sym_swap] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_sub] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_gte] = {
    .visible = true,
    .named = true,
  },
  [sym_lte] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [sym_print] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Char] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_grouping] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_local_bind] = {
    .visible = true,
    .named = true,
  },
  [sym_local_var] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_manual_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grouping_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_signature_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 4,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 10,
  [14] = 14,
  [15] = 10,
  [16] = 10,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 18,
  [27] = 20,
  [28] = 24,
  [29] = 19,
  [30] = 21,
  [31] = 25,
  [32] = 23,
  [33] = 17,
  [34] = 22,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 21,
  [51] = 17,
  [52] = 22,
  [53] = 19,
  [54] = 18,
  [55] = 23,
  [56] = 24,
  [57] = 18,
  [58] = 20,
  [59] = 25,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 68,
  [69] = 65,
  [70] = 68,
  [71] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '!', 4,
        '$', 61,
        '(', 87,
        ')', 89,
        '*', 44,
        '+', 42,
        '-', 43,
        '/', 45,
        ':', 85,
        '<', 49,
        '=', 5,
        '>', 48,
        '?', 86,
        'C', 14,
        'I', 17,
        '[', 36,
        ']', 37,
        'a', 18,
        'd', 11,
        'e', 16,
        'i', 12,
        'n', 20,
        'o', 23,
        'p', 24,
        's', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 4,
        '$', 61,
        '*', 44,
        '+', 42,
        '-', 43,
        '/', 45,
        ':', 85,
        '<', 49,
        '=', 5,
        '>', 48,
        '?', 86,
        '[', 36,
        ']', 37,
        'a', 72,
        'd', 82,
        'i', 69,
        'n', 74,
        'o', 77,
        'p', 78,
        's', 83,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 4,
        '$', 61,
        '*', 44,
        '+', 42,
        '-', 43,
        '/', 45,
        '<', 49,
        '=', 5,
        '>', 48,
        '[', 36,
        ']', 37,
        'a', 72,
        'd', 82,
        'e', 71,
        'i', 69,
        'n', 74,
        'o', 77,
        'p', 78,
        's', 83,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(89);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == 'C') ADVANCE(14);
      if (lookahead == 'I') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(46);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(88);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(52);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(62);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(91);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 'w') ADVANCE(7);
      END_STATE();
    case 31:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_positive_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_negative_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_dup);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_dup);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_swap);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_swap);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_add);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_sub);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_gte);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_lte);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_not);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_print);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_print);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_GT_DOLLAR);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_Int);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_Char);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 31},
  [66] = {.lex_state = 31},
  [67] = {.lex_state = 31},
  [68] = {.lex_state = 31},
  [69] = {.lex_state = 31},
  [70] = {.lex_state = 31},
  [71] = {.lex_state = 31},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [sym_positive_int] = ACTIONS(1),
    [sym_negative_int] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_dup] = ACTIONS(1),
    [sym_swap] = ACTIONS(1),
    [sym_add] = ACTIONS(1),
    [sym_sub] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_gte] = ACTIONS(1),
    [sym_lte] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_not] = ACTIONS(1),
    [sym_print] = ACTIONS(1),
    [anon_sym_GT_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_Char] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym_def] = STATE(47),
    [aux_sym_source_file_repeat1] = STATE(47),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_int] = STATE(50),
    [sym_grouping] = STATE(50),
    [sym_builtin] = STATE(50),
    [sym_local_bind] = STATE(50),
    [sym_local_var] = STATE(50),
    [sym_if] = STATE(50),
    [sym_expression] = STATE(61),
    [sym_manual_signature] = STATE(14),
    [sym_doc_signature] = STATE(14),
    [sym_positive_int] = ACTIONS(7),
    [sym_negative_int] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_dup] = ACTIONS(11),
    [sym_swap] = ACTIONS(11),
    [sym_add] = ACTIONS(13),
    [sym_sub] = ACTIONS(11),
    [sym_mul] = ACTIONS(13),
    [sym_div] = ACTIONS(13),
    [sym_eq] = ACTIONS(13),
    [sym_ne] = ACTIONS(13),
    [sym_gt] = ACTIONS(11),
    [sym_lt] = ACTIONS(11),
    [sym_gte] = ACTIONS(13),
    [sym_lte] = ACTIONS(13),
    [sym_and] = ACTIONS(11),
    [sym_or] = ACTIONS(11),
    [sym_not] = ACTIONS(11),
    [sym_print] = ACTIONS(11),
    [anon_sym_GT_DOLLAR] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_QMARK] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(3),
    [aux_sym_grouping_repeat1] = STATE(3),
    [sym_positive_int] = ACTIONS(27),
    [sym_negative_int] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(30),
    [anon_sym_RBRACK] = ACTIONS(33),
    [sym_dup] = ACTIONS(35),
    [sym_swap] = ACTIONS(35),
    [sym_add] = ACTIONS(38),
    [sym_sub] = ACTIONS(35),
    [sym_mul] = ACTIONS(38),
    [sym_div] = ACTIONS(38),
    [sym_eq] = ACTIONS(38),
    [sym_ne] = ACTIONS(38),
    [sym_gt] = ACTIONS(35),
    [sym_lt] = ACTIONS(35),
    [sym_gte] = ACTIONS(38),
    [sym_lte] = ACTIONS(38),
    [sym_and] = ACTIONS(35),
    [sym_or] = ACTIONS(35),
    [sym_not] = ACTIONS(35),
    [sym_print] = ACTIONS(35),
    [anon_sym_GT_DOLLAR] = ACTIONS(41),
    [anon_sym_DOLLAR] = ACTIONS(44),
    [anon_sym_if] = ACTIONS(47),
    [sym_identifier] = ACTIONS(50),
  },
  [STATE(4)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(5),
    [aux_sym_grouping_repeat1] = STATE(5),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(57),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(5)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(3),
    [aux_sym_grouping_repeat1] = STATE(3),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(71),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(6)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(7),
    [aux_sym_grouping_repeat1] = STATE(7),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(73),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(7)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(3),
    [aux_sym_grouping_repeat1] = STATE(3),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(75),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(8)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(9),
    [aux_sym_grouping_repeat1] = STATE(9),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(77),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(9)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(3),
    [aux_sym_grouping_repeat1] = STATE(3),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(79),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(10)] = {
    [sym_int] = STATE(50),
    [sym_grouping] = STATE(50),
    [sym_builtin] = STATE(50),
    [sym_local_bind] = STATE(50),
    [sym_local_var] = STATE(50),
    [sym_if] = STATE(50),
    [sym_expression] = STATE(57),
    [sym_positive_int] = ACTIONS(7),
    [sym_negative_int] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_dup] = ACTIONS(11),
    [sym_swap] = ACTIONS(11),
    [sym_add] = ACTIONS(13),
    [sym_sub] = ACTIONS(11),
    [sym_mul] = ACTIONS(13),
    [sym_div] = ACTIONS(13),
    [sym_eq] = ACTIONS(13),
    [sym_ne] = ACTIONS(13),
    [sym_gt] = ACTIONS(11),
    [sym_lt] = ACTIONS(11),
    [sym_gte] = ACTIONS(13),
    [sym_lte] = ACTIONS(13),
    [sym_and] = ACTIONS(11),
    [sym_or] = ACTIONS(11),
    [sym_not] = ACTIONS(11),
    [sym_print] = ACTIONS(11),
    [anon_sym_GT_DOLLAR] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(81),
    [sym_identifier] = ACTIONS(21),
  },
  [STATE(11)] = {
    [sym_int] = STATE(50),
    [sym_grouping] = STATE(50),
    [sym_builtin] = STATE(50),
    [sym_local_bind] = STATE(50),
    [sym_local_var] = STATE(50),
    [sym_if] = STATE(50),
    [sym_expression] = STATE(52),
    [sym_positive_int] = ACTIONS(7),
    [sym_negative_int] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_dup] = ACTIONS(11),
    [sym_swap] = ACTIONS(11),
    [sym_add] = ACTIONS(13),
    [sym_sub] = ACTIONS(11),
    [sym_mul] = ACTIONS(13),
    [sym_div] = ACTIONS(13),
    [sym_eq] = ACTIONS(13),
    [sym_ne] = ACTIONS(13),
    [sym_gt] = ACTIONS(11),
    [sym_lt] = ACTIONS(11),
    [sym_gte] = ACTIONS(13),
    [sym_lte] = ACTIONS(13),
    [sym_and] = ACTIONS(11),
    [sym_or] = ACTIONS(11),
    [sym_not] = ACTIONS(11),
    [sym_print] = ACTIONS(11),
    [anon_sym_GT_DOLLAR] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
  },
  [STATE(12)] = {
    [sym_int] = STATE(30),
    [sym_grouping] = STATE(30),
    [sym_builtin] = STATE(30),
    [sym_local_bind] = STATE(30),
    [sym_local_var] = STATE(30),
    [sym_if] = STATE(30),
    [sym_expression] = STATE(34),
    [sym_positive_int] = ACTIONS(53),
    [sym_negative_int] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [sym_dup] = ACTIONS(59),
    [sym_swap] = ACTIONS(59),
    [sym_add] = ACTIONS(61),
    [sym_sub] = ACTIONS(59),
    [sym_mul] = ACTIONS(61),
    [sym_div] = ACTIONS(61),
    [sym_eq] = ACTIONS(61),
    [sym_ne] = ACTIONS(61),
    [sym_gt] = ACTIONS(59),
    [sym_lt] = ACTIONS(59),
    [sym_gte] = ACTIONS(61),
    [sym_lte] = ACTIONS(61),
    [sym_and] = ACTIONS(59),
    [sym_or] = ACTIONS(59),
    [sym_not] = ACTIONS(59),
    [sym_print] = ACTIONS(59),
    [anon_sym_GT_DOLLAR] = ACTIONS(63),
    [anon_sym_DOLLAR] = ACTIONS(65),
    [anon_sym_if] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
  },
  [STATE(13)] = {
    [sym_int] = STATE(21),
    [sym_grouping] = STATE(21),
    [sym_builtin] = STATE(21),
    [sym_local_bind] = STATE(21),
    [sym_local_var] = STATE(21),
    [sym_if] = STATE(21),
    [sym_expression] = STATE(18),
    [sym_positive_int] = ACTIONS(83),
    [sym_negative_int] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(85),
    [sym_dup] = ACTIONS(87),
    [sym_swap] = ACTIONS(87),
    [sym_add] = ACTIONS(89),
    [sym_sub] = ACTIONS(87),
    [sym_mul] = ACTIONS(89),
    [sym_div] = ACTIONS(89),
    [sym_eq] = ACTIONS(89),
    [sym_ne] = ACTIONS(89),
    [sym_gt] = ACTIONS(87),
    [sym_lt] = ACTIONS(87),
    [sym_gte] = ACTIONS(89),
    [sym_lte] = ACTIONS(89),
    [sym_and] = ACTIONS(87),
    [sym_or] = ACTIONS(87),
    [sym_not] = ACTIONS(87),
    [sym_print] = ACTIONS(87),
    [anon_sym_GT_DOLLAR] = ACTIONS(91),
    [anon_sym_DOLLAR] = ACTIONS(93),
    [anon_sym_if] = ACTIONS(95),
    [sym_identifier] = ACTIONS(97),
  },
  [STATE(14)] = {
    [sym_int] = STATE(50),
    [sym_grouping] = STATE(50),
    [sym_builtin] = STATE(50),
    [sym_local_bind] = STATE(50),
    [sym_local_var] = STATE(50),
    [sym_if] = STATE(50),
    [sym_expression] = STATE(63),
    [sym_positive_int] = ACTIONS(7),
    [sym_negative_int] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_dup] = ACTIONS(11),
    [sym_swap] = ACTIONS(11),
    [sym_add] = ACTIONS(13),
    [sym_sub] = ACTIONS(11),
    [sym_mul] = ACTIONS(13),
    [sym_div] = ACTIONS(13),
    [sym_eq] = ACTIONS(13),
    [sym_ne] = ACTIONS(13),
    [sym_gt] = ACTIONS(11),
    [sym_lt] = ACTIONS(11),
    [sym_gte] = ACTIONS(13),
    [sym_lte] = ACTIONS(13),
    [sym_and] = ACTIONS(11),
    [sym_or] = ACTIONS(11),
    [sym_not] = ACTIONS(11),
    [sym_print] = ACTIONS(11),
    [anon_sym_GT_DOLLAR] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
  },
  [STATE(15)] = {
    [sym_int] = STATE(50),
    [sym_grouping] = STATE(50),
    [sym_builtin] = STATE(50),
    [sym_local_bind] = STATE(50),
    [sym_local_var] = STATE(50),
    [sym_if] = STATE(50),
    [sym_expression] = STATE(54),
    [sym_positive_int] = ACTIONS(7),
    [sym_negative_int] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_dup] = ACTIONS(11),
    [sym_swap] = ACTIONS(11),
    [sym_add] = ACTIONS(13),
    [sym_sub] = ACTIONS(11),
    [sym_mul] = ACTIONS(13),
    [sym_div] = ACTIONS(13),
    [sym_eq] = ACTIONS(13),
    [sym_ne] = ACTIONS(13),
    [sym_gt] = ACTIONS(11),
    [sym_lt] = ACTIONS(11),
    [sym_gte] = ACTIONS(13),
    [sym_lte] = ACTIONS(13),
    [sym_and] = ACTIONS(11),
    [sym_or] = ACTIONS(11),
    [sym_not] = ACTIONS(11),
    [sym_print] = ACTIONS(11),
    [anon_sym_GT_DOLLAR] = ACTIONS(15),
    [anon_sym_DOLLAR] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(81),
    [sym_identifier] = ACTIONS(21),
  },
  [STATE(16)] = {
    [sym_int] = STATE(21),
    [sym_grouping] = STATE(21),
    [sym_builtin] = STATE(21),
    [sym_local_bind] = STATE(21),
    [sym_local_var] = STATE(21),
    [sym_if] = STATE(21),
    [sym_expression] = STATE(26),
    [sym_positive_int] = ACTIONS(83),
    [sym_negative_int] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(85),
    [sym_dup] = ACTIONS(87),
    [sym_swap] = ACTIONS(87),
    [sym_add] = ACTIONS(89),
    [sym_sub] = ACTIONS(87),
    [sym_mul] = ACTIONS(89),
    [sym_div] = ACTIONS(89),
    [sym_eq] = ACTIONS(89),
    [sym_ne] = ACTIONS(89),
    [sym_gt] = ACTIONS(87),
    [sym_lt] = ACTIONS(87),
    [sym_gte] = ACTIONS(89),
    [sym_lte] = ACTIONS(89),
    [sym_and] = ACTIONS(87),
    [sym_or] = ACTIONS(87),
    [sym_not] = ACTIONS(87),
    [sym_print] = ACTIONS(87),
    [anon_sym_GT_DOLLAR] = ACTIONS(91),
    [anon_sym_DOLLAR] = ACTIONS(93),
    [anon_sym_if] = ACTIONS(95),
    [sym_identifier] = ACTIONS(97),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(101), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(99), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [30] = 3,
    ACTIONS(107), 1,
      anon_sym_else,
    ACTIONS(105), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(103), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [62] = 2,
    ACTIONS(111), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(109), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [92] = 2,
    ACTIONS(115), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(113), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [122] = 2,
    ACTIONS(119), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(117), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [152] = 2,
    ACTIONS(123), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(121), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [182] = 2,
    ACTIONS(127), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(125), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [212] = 2,
    ACTIONS(131), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(129), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [242] = 2,
    ACTIONS(135), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(133), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [272] = 2,
    ACTIONS(105), 12,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
    ACTIONS(103), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [302] = 2,
    ACTIONS(115), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(113), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [331] = 2,
    ACTIONS(131), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(129), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [360] = 2,
    ACTIONS(111), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(109), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [389] = 2,
    ACTIONS(119), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(117), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [418] = 2,
    ACTIONS(135), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(133), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [447] = 2,
    ACTIONS(127), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(125), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [476] = 2,
    ACTIONS(101), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(99), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [505] = 2,
    ACTIONS(123), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(121), 13,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [534] = 2,
    ACTIONS(139), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(137), 12,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [562] = 2,
    ACTIONS(143), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(141), 12,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [590] = 2,
    ACTIONS(147), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(145), 12,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [618] = 2,
    ACTIONS(151), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(149), 12,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [646] = 2,
    ACTIONS(155), 11,
      sym_dup,
      sym_swap,
      sym_sub,
      sym_gt,
      sym_lt,
      sym_and,
      sym_or,
      sym_not,
      sym_print,
      anon_sym_if,
      sym_identifier,
    ACTIONS(153), 12,
      sym_positive_int,
      sym_negative_int,
      anon_sym_LBRACK,
      sym_add,
      sym_mul,
      sym_div,
      sym_eq,
      sym_ne,
      sym_gte,
      sym_lte,
      anon_sym_GT_DOLLAR,
      anon_sym_DOLLAR,
  [674] = 3,
    ACTIONS(157), 2,
      anon_sym_DASH_GT,
      anon_sym_RPAREN,
    ACTIONS(159), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(40), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [687] = 3,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(40), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [699] = 3,
    ACTIONS(166), 1,
      anon_sym_DASH_GT,
    ACTIONS(164), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(44), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [711] = 3,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(45), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [723] = 3,
    ACTIONS(170), 1,
      anon_sym_DASH_GT,
    ACTIONS(164), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(40), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [735] = 3,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(40), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [747] = 3,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 2,
      anon_sym_Int,
      anon_sym_Char,
    STATE(41), 2,
      sym_type,
      aux_sym_signature_repeat1,
  [759] = 3,
    ACTIONS(5), 1,
      anon_sym_def,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    STATE(49), 2,
      sym_def,
      aux_sym_source_file_repeat1,
  [770] = 1,
    ACTIONS(176), 4,
      anon_sym_DASH_GT,
      anon_sym_RPAREN,
      anon_sym_Int,
      anon_sym_Char,
  [777] = 3,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_def,
    STATE(49), 2,
      sym_def,
      aux_sym_source_file_repeat1,
  [788] = 1,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [794] = 1,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [800] = 1,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [806] = 1,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [812] = 1,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [818] = 1,
    ACTIONS(125), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [824] = 1,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [830] = 2,
    ACTIONS(183), 1,
      anon_sym_else,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_def,
  [838] = 1,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [844] = 1,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_else,
  [850] = 2,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_signature,
  [857] = 1,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      anon_sym_def,
  [862] = 2,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym_signature,
  [869] = 1,
    ACTIONS(189), 2,
      ts_builtin_sym_end,
      anon_sym_def,
  [874] = 1,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
  [878] = 1,
    ACTIONS(193), 1,
      sym_identifier,
  [882] = 1,
    ACTIONS(195), 1,
      sym_identifier,
  [886] = 1,
    ACTIONS(197), 1,
      sym_identifier,
  [890] = 1,
    ACTIONS(199), 1,
      sym_identifier,
  [894] = 1,
    ACTIONS(201), 1,
      sym_identifier,
  [898] = 1,
    ACTIONS(203), 1,
      sym_identifier,
  [902] = 1,
    ACTIONS(205), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 30,
  [SMALL_STATE(19)] = 62,
  [SMALL_STATE(20)] = 92,
  [SMALL_STATE(21)] = 122,
  [SMALL_STATE(22)] = 152,
  [SMALL_STATE(23)] = 182,
  [SMALL_STATE(24)] = 212,
  [SMALL_STATE(25)] = 242,
  [SMALL_STATE(26)] = 272,
  [SMALL_STATE(27)] = 302,
  [SMALL_STATE(28)] = 331,
  [SMALL_STATE(29)] = 360,
  [SMALL_STATE(30)] = 389,
  [SMALL_STATE(31)] = 418,
  [SMALL_STATE(32)] = 447,
  [SMALL_STATE(33)] = 476,
  [SMALL_STATE(34)] = 505,
  [SMALL_STATE(35)] = 534,
  [SMALL_STATE(36)] = 562,
  [SMALL_STATE(37)] = 590,
  [SMALL_STATE(38)] = 618,
  [SMALL_STATE(39)] = 646,
  [SMALL_STATE(40)] = 674,
  [SMALL_STATE(41)] = 687,
  [SMALL_STATE(42)] = 699,
  [SMALL_STATE(43)] = 711,
  [SMALL_STATE(44)] = 723,
  [SMALL_STATE(45)] = 735,
  [SMALL_STATE(46)] = 747,
  [SMALL_STATE(47)] = 759,
  [SMALL_STATE(48)] = 770,
  [SMALL_STATE(49)] = 777,
  [SMALL_STATE(50)] = 788,
  [SMALL_STATE(51)] = 794,
  [SMALL_STATE(52)] = 800,
  [SMALL_STATE(53)] = 806,
  [SMALL_STATE(54)] = 812,
  [SMALL_STATE(55)] = 818,
  [SMALL_STATE(56)] = 824,
  [SMALL_STATE(57)] = 830,
  [SMALL_STATE(58)] = 838,
  [SMALL_STATE(59)] = 844,
  [SMALL_STATE(60)] = 850,
  [SMALL_STATE(61)] = 857,
  [SMALL_STATE(62)] = 862,
  [SMALL_STATE(63)] = 869,
  [SMALL_STATE(64)] = 874,
  [SMALL_STATE(65)] = 878,
  [SMALL_STATE(66)] = 882,
  [SMALL_STATE(67)] = 886,
  [SMALL_STATE(68)] = 890,
  [SMALL_STATE(69)] = 894,
  [SMALL_STATE(70)] = 898,
  [SMALL_STATE(71)] = 902,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_grouping_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouping, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 4, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 4, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_bind, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_bind, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_var, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_var, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouping, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_signature, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doc_signature, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manual_signature, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_manual_signature, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_signature_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_signature_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 4, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_adventus(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "adventus",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
